<a href="https://colab.research.google.com/github/norman-AI-2025/data-science-norman/blob/main/week2tuto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[0,1,2],[3,4,5]])
print(arr1)

[[0 1 2]
 [3 4 5]]


In [ ]:
arr2=np.random.rand(3,4)
print(arr2)


[[9.81970573e-01 1.48725562e-02 8.40979960e-02 4.08033126e-01]
 [1.96089876e-04 3.82226970e-01 2.77037105e-01 3.71067983e-01]
 [5.82547084e-01 5.91577763e-01 5.17535747e-01 9.40527713e-01]]


In [ ]:
arr_zero = np.zeros((3,4))
print(arr_zero)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr_ones = np.ones((3,4))
print(arr_ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr_ran = np.random.rand(6,3)
print(arr_ran.T)

[[0.08491941 0.52532682 0.41267635 0.51604639 0.11420606 0.64025397]
 [0.4204971  0.56736231 0.59885876 0.34514809 0.33490116 0.60863538]
 [0.69805886 0.06119301 0.01412019 0.61073644 0.10452548 0.50722542]]


In [ ]:
arr_dot1 = np.random.rand(2,3)
arr_dot2 = np.random.rand(3,4)
print(arr_dot1 , "\n\n" ,arr_dot2)
dot_product = np.dot(arr_dot1,arr_dot2)
print("\n\n",dot_product)

[[0.75621413 0.50471276 0.38036883]
 [0.91973512 0.13234706 0.16137186]] 

 [[0.12548307 0.26976982 0.43875861 0.13681349]
 [0.53036376 0.13135198 0.17878887 0.68841171]
 [0.33253937 0.54178236 0.63660364 0.48314491]]


 [[0.48906105 0.4763759  0.66417667 0.63468374]
 [0.23926577 0.35292925 0.5299338  0.29490743]]
