In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[0,1,2],[3,4,5]])
print(arr1)

[[0 1 2]
 [3 4 5]]


In [ ]:
arr2=np.random.rand(3,4)
print(arr2)

[[0.94963648 0.35101275 0.10394694 0.12510409]
 [0.37047396 0.67027029 0.06969672 0.21693441]
 [0.33346691 0.32673125 0.68404974 0.9070705 ]]


In [ ]:
arr_zero = np.zeros((3,4))
print(arr_zero)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr_ones = np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr_ran = np.random.rand(6,3)
print(arr_ran.T)

[[0.44378464 0.53401852 0.50890115 0.31829263 0.64286611 0.62832205]
 [0.48398173 0.50633716 0.46750224 0.1463655  0.74341536 0.03484009]
 [0.61056675 0.90146565 0.08437876 0.79346417 0.95472572 0.64831545]]


In [ ]:
arr_dot1 = np.random.rand(2,3)
arr_dot2 = np.random.rand(3,4)
print(arr_dot1 , "\n\n" ,arr_dot2)
dot_product = np.dot(arr_dot1,arr_dot2)
print("\n\n",dot_product)


[[0.32998864 0.05844272 0.67821342]
 [0.18657981 0.12744086 0.42093752]] 

 [[0.68052077 0.96562714 0.82040421 0.40275967]
 [0.8508008  0.33218268 0.50658438 0.24450318]
 [0.43000307 0.01052057 0.37485475 0.2512246 ]]


 [[0.56592108 0.34519483 0.55456175 0.31757944]
 [0.41640265 0.22692868 0.37542084 0.21205638]]


In [64]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [65]:
!ls /content/drive/MyDrive

'Colab Notebooks'   git_repos


In [68]:
%cd /content/drive/MyDrive/Colab\Notebooks

[Errno 2] No such file or directory: '/content/drive/MyDrive/ColabNotebooks'
/content/drive/MyDrive/Colab Notebooks


In [69]:
%cd "/content/drive/MyDrive/Colab Notebooks"

/content/drive/MyDrive/Colab Notebooks


In [70]:
!ls

lecture_week3.ipynb  numpy_week3.ipynb	Setup.ipynb  week2_tuto.ipynb


In [72]:
%cd /content
!git clone https://github.com/norman-AI-2025/data-science-norman.git


/content
fatal: destination path 'data-science-norman' already exists and is not an empty directory.
/content/data-science-norman


In [74]:

!git clone https://github.com/norman-AI-2025/data-science-norman.git

fatal: destination path 'data-science-norman' already exists and is not an empty directory.


In [75]:
%cd /content/data-science-norman

/content/data-science-norman


In [76]:
!ls

python_basics.ipynb  README.md


In [77]:
!cp /content/drive/MyDrive/Colab\ Notebooks/week2_tutoi.ipynb

cp: missing destination file operand after '/content/drive/MyDrive/Colab Notebooks/week2_tutoi.ipynb'
Try 'cp --help' for more information.


In [78]:
!pwd

/content/data-science-norman


In [79]:
!ls

python_basics.ipynb  README.md


In [80]:
%cd \content

[Errno 2] No such file or directory: 'content'
/content/data-science-norman


In [81]:
%cd /content

/content


In [82]:
!git clone https://github.com/norman-AI-2025/data-science-norman.git

fatal: destination path 'data-science-norman' already exists and is not an empty directory.


In [83]:
%cd /content/data-science-norman

/content/data-science-norman


In [86]:
!cp "/content/drive/MyDrive/Colab Notebooks/week2_tutoi.ipynb"

cp: missing destination file operand after '/content/drive/MyDrive/Colab Notebooks/week2_tutoi.ipynb'
Try 'cp --help' for more information.


In [87]:
!cp /content/drive/MyDrive/ColabNotebooks/week2_tutoi.ipynb .

cp: cannot stat '/content/drive/MyDrive/ColabNotebooks/week2_tutoi.ipynb': No such file or directory


In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [90]:
%cd /content/data-science-norman
!cp "/content/drive/MyDrive/ColabNotebooks/week2_tuto.ipynb" .

/content/data-science-norman


In [91]:
!ls

python_basics.ipynb  README.md	week2_tuto.ipynb
